name: Check Links

on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check HTML links
        uses: lycheeverse/lychee-action@v2
        with:
          args: './**/*.html'