name: Reset scam-check-now pages

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete all scam-check-now pages except main page
        run: |
          cd scam-check-now

          for item in *; do
            if [ "$item" != "is-this-a-scam" ]; then
              rm -rf "$item"
            fi
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Reset scam-check-now folder keeping only is-this-a-scam"
            git push
          fi